REM*************************************************************
REM12345678901234567890123456789012345678901234567890123456789012345678901234567890
REM AGREEMENT  : F4914001, DISPATCH CONSIGNMENT
REM SOURCE     : EPU002
REM DESTINATION: CNS                              
REM OBJECT     : CSM                                                      
REM DESCRIPTION: SEND OF TABLE CONSIGNMENT_%
REM MADE BY    : ULF MATTSSON PURCHASING IT                             
REM CREATED    : 010516                                 
REM IDRS FLOW  : \TOS\3_0\OBJECTS\CSM\DOCUMENTATION\CsmSpec.doc
REM CHANGED                                                            
REM WHO      WHEN      WHAT                                            
REM -----    -------   ------------------------------------------
REM MAFZ     081006        del. blank line changed to REM due to 10g migration
REM BISV     090123        added select of LD_SEQNO
REM BESV  
REM ANJOA2   140825        added ORD_NO_ISOM, ORDL_NO_ISOM and I table names IKEA00314758   
REM*************************************************************
REM WHENEVER SQLERROR EXIT 16 ROLLBACK                                    
WHENEVER SQLERROR EXIT SQL.SQLCODE
DELETE F4914001_T
/
DELETE F4914002_T
/
DELETE F4914003_T
/
UPDATE run_idrs
   SET fix_date  = SYSDATE
 WHERE idrs_name = 'F4914001'     
/   
UPDATE consignment_t
   SET SEND_MARK_CNS_DSP = 'Y'
 WHERE (BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO) IN 
        (SELECT BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO
           FROM RUN_IDRS_T,
                F4914001_V 
          WHERE F4914001_V.UPD_DATE > RUN_IDRS_T.RUN_DATE - 0.5
            AND RUN_IDRS_T.IDRS_NAME = 'F4914001'
            AND F4914001_V.SEND_MARK_CNS_DSP IS NULL)
/
INSERT INTO F4914001_T
SELECT RECORD_TYPE, TRANS_DATE, 
       BU_CODE_CRE, BU_TYPE_CRE, CSM_NO,
       BU_CODE_CNOR, BU_TYPE_CNOR, BUA_NO_CNOR, 
       BU_CODE_CNEE, BU_TYPE_CNEE, BUA_NO_CNEE,
       BU_CODE_PUP, BU_TYPE_PUP, BUA_NO_PUP, 
       TOD_CODE, TOD_TXT_PLACE, MOT_CODE, 
       DSP_DAY_PLAN, DSP_DAY,
       TRPT_WEI_ORD, TRPT_VOL_ORD,
       INVO_NO, CERT_NO,
       NOTI_SEQNO, CRE_DAY_CSM,
       LU_ID_REF, BL_ID, 
       F4914001_V.SRC_NAME_INS, 
       PACK_NOF_CSM, CP_FLAG,
       BU_CODE_TSO, BU_TYPE_TSO,
       BU_CODE_CP, BU_TYPE_CP, SEAL_NO, SEAL_NO_2, CSM_VOL_GRO_FRZ, CSM_WEI_GRO_FRZ,
       CSM_WEI_NET_FRZ, UOM_CODE_WEI, UOM_CODE_VOL, LD_SEQNO,
       PROP_CRE_SYSTEM, CSM_VOL_NET_FRZ,
       CSM_VOL_PAL_FRZ, CSM_WEI_PAL_FRZ
  FROM F4914001_V,  
       RUN_IDRS_T
 WHERE F4914001_V.UPD_DATE > RUN_IDRS_T.RUN_DATE - 0.5
   AND RUN_IDRS_T.IDRS_NAME = 'F4914001'
    AND F4914001_V.SEND_MARK_CNS_DSP = 'Y'
/

SELECT RECORD_TYPE, TRANS_DATE, 
       BU_CODE_CRE, BU_TYPE_CRE, CSM_NO,
       BU_CODE_CNOR, BU_TYPE_CNOR, BUA_NO_CNOR, 
       BU_CODE_CNEE, BU_TYPE_CNEE, BUA_NO_CNEE,
       BU_CODE_PUP, BU_TYPE_PUP, BUA_NO_PUP, 
       TOD_CODE, TOD_TXT_PLACE, MOT_CODE, 
       DSP_DAY_PLAN, DSP_DAY,
       TRPT_WEI_ORD, TRPT_VOL_ORD,
       INVO_NO, CERT_NO,
       NOTI_SEQNO, CRE_DAY_CSM,
       LU_ID_REF, BL_ID, 
       SRC_NAME_INS, 
       PACK_NOF_CSM, CP_FLAG,
       BU_CODE_TSO, BU_TYPE_TSO,
       BU_CODE_CP, BU_TYPE_CP, SEAL_NO, SEAL_NO_2, CSM_VOL_GRO_FRZ, CSM_WEI_GRO_FRZ,
       CSM_WEI_NET_FRZ, UOM_CODE_WEI, UOM_CODE_VOL, LD_SEQNO,
       PROP_CRE_SYSTEM, CSM_VOL_NET_FRZ,
       CSM_VOL_PAL_FRZ, CSM_WEI_PAL_FRZ
FROM F4914001_T
/* SUPPLIER = PUR                */
/* TABLE =  I_4914051            */
/
INSERT INTO F4914002_T
SELECT RECORD_TYPE, TRANS_DATE, 
       BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO, CSML_NO, 
       ITEM_ID, ITEM_TYPE, ITEM_QTY_DSP, 
       BU_CODE_CRE_ORD, BU_TYPE_CRE_ORD, 
       ORD_NO, ORDL_NO, 
       PUA_NO, PUA_VER_NO, 
       CREATE_DATE_ORD, BU_CODE_RCV, BU_TYPE_RCV, 
       SEQ_NO_ORD, SRC_NAME_ORD, 
       STO_NO_DDC, ORD_NO_DDC, ORD_NO_COS, 
       ORD_TYPE, DEL_YW, GBA_CODE, SRC_NAME_INS, ORD_TYPE_ITS, PM_CODE, 
       PG_CODE, SUB_ADR_NO, PACK_NOF_CSML, CSML_VOL_GRO_FRZ, CSML_WEI_GRO_FRZ,
       CSML_WEI_NET_FRZ, UOM_CODE_QTY, UOM_CODE_WEI, UOM_CODE_VOL, 
       CSML_VOL_NET_FRZ, PROD_DATE,
       HM_FLAG, CSML_WEI_PAL_FRZ,CSML_VOL_PAL_FRZ,ORD_NO_ISOM,ORDL_NO_ISOM
  FROM F4914002_V
 WHERE (BU_CODE_CRE, BU_TYPE_CRE, CSM_NO) IN 
        (SELECT BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO
           FROM RUN_IDRS_T,
                F4914001_V
          WHERE F4914001_V.UPD_DATE > RUN_IDRS_T.RUN_DATE - 0.5
            AND RUN_IDRS_T.IDRS_NAME = 'F4914001'
             AND F4914001_V.SEND_MARK_CNS_DSP = 'Y')
/
select RECORD_TYPE, TRANS_DATE, 
       BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO, CSML_NO, 
       ITEM_ID, ITEM_TYPE, ITEM_QTY_DSP, 
       BU_CODE_CRE_ORD, BU_TYPE_CRE_ORD, 
       ORD_NO, ORDL_NO, 
       PUA_NO, PUA_VER_NO, 
       CREATE_DATE_ORD, BU_CODE_RCV, BU_TYPE_RCV, 
       SEQ_NO_ORD, SRC_NAME_ORD, 
       STO_NO_DDC, ORD_NO_DDC, ORD_NO_COS, 
       ORD_TYPE, DEL_YW, GBA_CODE, SRC_NAME_INS, ORD_TYPE_ITS, PM_CODE, 
       PG_CODE, SUB_ADR_NO, PACK_NOF_CSML, CSML_VOL_GRO_FRZ, CSML_WEI_GRO_FRZ,
       CSML_WEI_NET_FRZ, UOM_CODE_QTY, UOM_CODE_WEI, UOM_CODE_VOL, 
       CSML_VOL_NET_FRZ, PROD_DATE,
       HM_FLAG, CSML_WEI_PAL_FRZ,CSML_VOL_PAL_FRZ,ORD_NO_ISOM,ORDL_NO_ISOM
from F4914002_T
/* SUPPLIER = PUR                */
/* TABLE =  I_4914052            */
/
INSERT INTO F4914003_T
SELECT RECORD_TYPE, TRANS_DATE, 
       BU_CODE_CRE, BU_TYPE_CRE, CSM_NO, 
       MSG_ID_CSM, MSG_TXT_CSM, SRC_NAME_INS
  FROM F4914003_V
 WHERE (BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO) IN 
        (SELECT BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO
           FROM RUN_IDRS_T,
                F4914001_V
          WHERE F4914001_V.UPD_DATE > RUN_IDRS_T.RUN_DATE - 0.5
            AND RUN_IDRS_T.IDRS_NAME = 'F4914001'
             AND F4914001_V.SEND_MARK_CNS_DSP = 'Y')
/
select RECORD_TYPE, TRANS_DATE, 
       BU_CODE_CRE, BU_TYPE_CRE, CSM_NO, 
       MSG_ID_CSM, MSG_TXT_CSM, SRC_NAME_INS
from F4914003_T
/* SUPPLIER = PUR                */
/* TABLE =  I_4914053            */
/* DEST = PT3CNS */
/* TIMESTAMP */
/
UPDATE consignment_t
   SET SEND_DATE_CNS_DSP = SYSDATE,
        SEND_MARK_CNS_DSP = NULL
 WHERE (BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO) IN 
        (SELECT BU_CODE_CRE_CSM, BU_TYPE_CRE_CSM, CSM_NO
           FROM RUN_IDRS_T,
                F4914001_V
          WHERE F4914001_V.UPD_DATE > RUN_IDRS_T.RUN_DATE - 0.5
            AND RUN_IDRS_T.IDRS_NAME         = 'F4914001'
                AND F4914001_V.SEND_MARK_CNS_DSP = 'Y')
/   
UPDATE run_idrs
   SET run_date      = fix_date,
       run_date_prev = run_date  
 WHERE idrs_name     = 'F4914001'
/
